# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-20 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20190621_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.TextField(default='请输入内容'),
        ),
    ]
