# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-20 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20190621_0146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '内容'},
        ),
    ]
